# NumPy Fundamentals: Array Basics

Until now, we have focused on Python basics and built-in functions. In order to access specific packages, like NumPy, we need to import them like so:

In [27]:
# import the numpy as the shorthand np
import numpy as np

Using a standardized alias like `np` saves us a little bit of time later.

## NumPy Arrays
The most basic data structure in NumPy is an `ndarray`. 
The name `ndarray` comes from the fact that they can store "n dimensions" of data.

Lastly, arrays are similar to lists in that they can be indexed with the same syntax; however, unlike lists, NumPy arrays must contain numeric data types. 

Let's start by defining a simple 1D array, which can also be referred to as a vector:

In [17]:
# Create a vector from a list
my_list = [1,2,3,4]
my_vector = np.array(my_list)
print(type(my_list))
print(type(my_vector))

<class 'list'>
<class 'numpy.ndarray'>


Using what we learned from Module 1, we can index the list and the vector exactly the same way:

In [15]:
# Index the first elements:
print(f"The first element of the list: { my_list[0] }")
print(f"The first element of the vector: { my_vector[0] }")

The first element of the list: 1
The first element of the vector: 1


### Silas -- Please write/demonstrate the following:
1. Introduce 2D indexing and connect it back to how we learned `[][]` syntax in the Module 1 lecture
2. Show basic 2D slicing
3. Modifying elements by indexing them still works the same for 2D arrays

In [4]:
my_nested_list = [[5,6], [7,8]]
my_2d_array = np.array(my_nested_list)
print(my_2d_array)

[[5 6]
 [7 8]]


### Silas -- Please write/demonstrate the following:
1. Introduce 3D indexing
2. Show basic 3D slicing
2. Modifying elements by indexing them still works the same for 3D arrays

In [29]:
my_3d_array = np.array([my_nested_list, [[9,10], [11,12]]])
print(my_3d_array)

[[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## Doing Math With Arrays

### Peter -- Please show the following:
1. scalar multiplication of a simple vector
2. introduce basic vector/elementwise math by showing: 
    - `u * u = u**2`
    - `u * v` = ???
    - `v/u` = ???

In [22]:
u = np.array([1,2,3])
v = np.array([5,10,15])

## Common Array Constructors

### Peter -- Please demonstrate the functionality and use cases for the following `np.array` constructors:
- `np.zeros()`
- `np.ones()`
- `np.identity()` and explain what an identity matrix is 
- `np.nan()` and explain what `np.nan`/`NaN` is 
- `np.empty()` and highlight that the output is not exactly zero
- `np.full()`
- `np.tile()`

Lastly, please compare `np.linspace` vs. `arange` vs. `range()`

## Determining Matrix Size

#### The `len()` function:

The `len()` function in Python is short for "length". This function will return the number of elements in a collection. Let's see a quick example using a list: 

In [25]:
my_list = [1, 2, 3]

print(len(my_list))

3


#### Why `len(my_list) = len(my_vector)` but `len(my_nested_list) != (my_2d_array)`:

In addition to `my_list`, let's create `my_vector`. We will see that `len(my_list) = len(my_vector)` because they are both one-dimensional collections. In this case they each have 3 elements. 

In [21]:
my_list = [1, 2, 3]
my_vector = [4, 5, 6]

print(f"List length: {len(my_list)}")
print(f"Vector length: {len(my_vector)}")

List length: 3
Vector length: 3


Now let's create and compare `my_nested_list` and `my_2d_array`. As we saw, `len()` counts the number of elements in a list; in a nested list, the elements are more lists. In the 2D array, `len()` counts the number of rows. So even though we see six total elements in each, `len(my_nested_list) != len(my_2d_array)` because of the structure of the rows and columns in the array. 

In [24]:
my_nested_list = [[1, 2], [3, 4, 5], [6]]
my_2d_array = np.array([[7, 8, 9], [10, 11, 12]])

print(f"{my_nested_list}   Nested list length: {len(my_nested_list)} \n")
print(f"{my_2d_array}      2D array length: {len(my_2d_array)}")

[[1, 2], [3, 4, 5], [6]]   Nested list length: 3 

[[ 7  8  9]
 [10 11 12]]      2D array length: 2


#### The `.shape()` and `.size()` array functions:

With 2D arrays, we have a couple of functions similar to `len()`. We can use `.size` to return the total number of elements and we can use `.shape` to return the total number of rows and columns.

`.size` is useful for if we want to iterate over every element in the array. `.shape` is useful for if we want to restructure the array or perform some matrix operation. 

In the following example, we have 6 total elements in the array, so `.size` will return 6. The array is organized into 3 rows and 2 columns, so `.shape` will return (2, 3).

In [28]:
my_2d_array = np.array([[4, 5], [6, 7], [8, 9]])

print(f"{my_2d_array} \n")
print(f"Size: {my_2d_array.size}")
print(f"Shape: {my_2d_array.shape}")

[[4 5]
 [6 7]
 [8 9]] 

Size: 6
Shape: (3, 2)
